<?php

namespace Database\Seeders;

use App\Models\CountryCode;
use Illuminate\Database\Seeder;

class CountryCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = array(
            array('country_code' => 'DZ', 'mobile_code' => 213, 'name' => 'Algeria(+213)'),
            array('country_code' => 'AD', 'mobile_code' => 376, 'name' => 'Andorra(+376)'),
            array('country_code' => 'AO', 'mobile_code' => 244, 'name' => 'Angola(+244)'),
            array('country_code' => 'AI', 'mobile_code' => 1264, 'name' => 'Anguilla(+1264)'),
            array('country_code' => 'AG', 'mobile_code' => 1268, 'name' => 'Antigua & Barbuda(+1268)'),
            array('country_code' => 'AR', 'mobile_code' => 54, 'name' => 'Argentina(+54)'),
            array('country_code' => 'AM', 'mobile_code' => 374, 'name' => 'Armenia(+374)'),
            array('country_code' => 'AW', 'mobile_code' => 297, 'name' => 'Aruba(+297)'),
            array('country_code' => 'AU', 'mobile_code' => 61, 'name' => 'Australia(+61)'),
            array('country_code' => 'AT', 'mobile_code' => 43, 'name' => 'Austria(+43)'),
            array('country_code' => 'AZ', 'mobile_code' => 994, 'name' => 'Azerbaijan(+994)'),
            array('country_code' => 'BS', 'mobile_code' => 1242, 'name' => 'Bahamas(+1242)'),
            array('country_code' => 'BH', 'mobile_code' => 973, 'name' => 'Bahrain(+973)'),
            array('country_code' => 'BD', 'mobile_code' => 880, 'name' => 'Bangladesh(+880)'),
            array('country_code' => 'BB', 'mobile_code' => 1246, 'name' => 'Barbados(+1246)'),
            array('country_code' => 'BY', 'mobile_code' => 375, 'name' => 'Belarus(+375)'),
            array('country_code' => 'BE', 'mobile_code' => 32, 'name' => 'Belgium(+32)'),
            array('country_code' => 'BZ', 'mobile_code' => 501, 'name' => 'Belize(+501)'),
            array('country_code' => 'BJ', 'mobile_code' => 229, 'name' => 'Benin(+229)'),
            array('country_code' => 'BM', 'mobile_code' => 1441, 'name' => 'Bermuda(+1441)'),
            array('country_code' => 'BT', 'mobile_code' => 975, 'name' => 'Bhutan(+975)'),
            array('country_code' => 'BO', 'mobile_code' => 591, 'name' => 'Bolivia(+591)'),
            array('country_code' => 'BA', 'mobile_code' => 387, 'name' => 'BosniaHerzegovina(+387)'),
            array('country_code' => 'BW', 'mobile_code' => 267, 'name' => 'Botswana(+267)'),
            array('country_code' => 'BR', 'mobile_code' => 55, 'name' => 'Brazil(+55)'),
            array('country_code' => 'BN', 'mobile_code' => 673, 'name' => 'Brunei(+673)'),
            array('country_code' => 'BG', 'mobile_code' => 359, 'name' => 'Bulgaria(+359)'),
            array('country_code' => 'BF', 'mobile_code' => 226, 'name' => 'BurkinaFaso(+226)'),
            array('country_code' => 'BI', 'mobile_code' => 257, 'name' => 'Burundi(+257)'),
            array('country_code' => 'KH', 'mobile_code' => 855, 'name' => 'Cambodia(+855)'),
            array('country_code' => 'CM', 'mobile_code' => 237, 'name' => 'Cameroon(+237)'),
            array('country_code' => 'CA', 'mobile_code' => 1, 'name' => 'Canada(+1)'),
            array('country_code' => 'CV', 'mobile_code' => 238, 'name' => 'CapeVerdeIslands(+238)'),
            array('country_code' => 'KY', 'mobile_code' => 1345, 'name' => 'CaymanIslands(+1345)'),
            array('country_code' => 'CF', 'mobile_code' => 236, 'name' => 'CentralAfricanRepublic(+236)'),
            array('country_code' => 'CL', 'mobile_code' => 56, 'name' => 'Chile(+56)'),
            array('country_code' => 'CN', 'mobile_code' => 86, 'name' => 'China(+86)'),
            array('country_code' => 'CO', 'mobile_code' => 57, 'name' => 'Colombia(+57)'),
            array('country_code' => 'KM', 'mobile_code' => 269, 'name' => 'Comoros(+269)'),
            array('country_code' => 'CG', 'mobile_code' => 242, 'name' => 'Congo(+242)'),
            array('country_code' => 'CK', 'mobile_code' => 682, 'name' => 'CookIslands(+682)'),
            array('country_code' => 'CR', 'mobile_code' => 506, 'name' => 'CostaRica(+506)'),
            array('country_code' => 'HR', 'mobile_code' => 385, 'name' => 'Croatia(+385)'),
            array('country_code' => 'CU', 'mobile_code' => 53, 'name' => 'Cuba(+53)'),
            array('country_code' => 'CY', 'mobile_code' => 90392, 'name' => 'CyprusNorth(+90392)'),
            array('country_code' => 'CY', 'mobile_code' => 357, 'name' => 'CyprusSouth(+357)'),
            array('country_code' => 'CZ', 'mobile_code' => 42, 'name' => 'CzechRepublic(+42)'),
            array('country_code' => 'DK', 'mobile_code' => 45, 'name' => 'Denmark(+45)'),
            array('country_code' => 'DJ', 'mobile_code' => 253, 'name' => 'Djibouti(+253)'),
            array('country_code' => 'DM', 'mobile_code' => 1809, 'name' => 'Dominica(+1809)'),
            array('country_code' => 'DO', 'mobile_code' => 1809, 'name' => 'DominicanRepublic(+1809)'),
            array('country_code' => 'EC', 'mobile_code' => 593, 'name' => 'Ecuador(+593)'),
            array('country_code' => 'EG', 'mobile_code' => 20, 'name' => 'Egypt(+20)'),
            array('country_code' => 'SV', 'mobile_code' => 503, 'name' => 'ElSalvador(+503)'),
            array('country_code' => 'GQ', 'mobile_code' => 240, 'name' => 'EquatorialGuinea(+240)'),
            array('country_code' => 'ER', 'mobile_code' => 291, 'name' => 'Eritrea(+291)'),
            array('country_code' => 'EE', 'mobile_code' => 372, 'name' => 'Estonia(+372)'),
            array('country_code' => 'ET', 'mobile_code' => 251, 'name' => 'Ethiopia(+251)'),
            array('country_code' => 'FK', 'mobile_code' => 500, 'name' => 'FalklandIslands(+500)'),
            array('country_code' => 'FO', 'mobile_code' => 298, 'name' => 'FaroeIslands(+298)'),
            array('country_code' => 'FJ', 'mobile_code' => 679, 'name' => 'Fiji(+679)'),
            array('country_code' => 'FI', 'mobile_code' => 358, 'name' => 'Finland(+358)'),
            array('country_code' => 'FR', 'mobile_code' => 33, 'name' => 'France(+33)'),
            array('country_code' => 'GF', 'mobile_code' => 594, 'name' => 'FrenchGuiana(+594)'),
            array('country_code' => 'PF', 'mobile_code' => 689, 'name' => 'FrenchPolynesia(+689)'),
            array('country_code' => 'GA', 'mobile_code' => 241, 'name' => 'Gabon(+241)'),
            array('country_code' => 'GM', 'mobile_code' => 220, 'name' => 'Gambia(+220)'),
            array('country_code' => 'GE', 'mobile_code' => 7880, 'name' => 'Georgia(+7880)'),
            array('country_code' => 'DE', 'mobile_code' => 49, 'name' => 'Germany(+49)'),
            array('country_code' => 'GH', 'mobile_code' => 233, 'name' => 'Ghana(+233)'),
            array('country_code' => 'GI', 'mobile_code' => 350, 'name' => 'Gibraltar(+350)'),
            array('country_code' => 'GR', 'mobile_code' => 30, 'name' => 'Greece(+30)'),
            array('country_code' => 'GL', 'mobile_code' => 299, 'name' => 'Greenland(+299)'),
            array('country_code' => 'GD', 'mobile_code' => 1473, 'name' => 'Grenada(+1473)'),
            array('country_code' => 'GP', 'mobile_code' => 590, 'name' => 'Guadeloupe(+590)'),
            array('country_code' => 'GU', 'mobile_code' => 671, 'name' => 'Guam(+671)'),
            array('country_code' => 'GT', 'mobile_code' => 502, 'name' => 'Guatemala(+502)'),
            array('country_code' => 'GN', 'mobile_code' => 224, 'name' => 'Guinea(+224)'),
            array('country_code' => 'GW', 'mobile_code' => 245, 'name' => 'Guinea-Bissau(+245'),
            array('country_code' => 'GY', 'mobile_code' => 592, 'name' => 'Guyana(+592)'),
            array('country_code' => 'HT', 'mobile_code' => 509, 'name' => 'Haiti(+509)'),
            array('country_code' => 'HN', 'mobile_code' => 504, 'name' => 'Honduras(+504)'),
            array('country_code' => 'HK', 'mobile_code' => 852, 'name' => 'HongKong(+852)'),
            array('country_code' => 'HU', 'mobile_code' => 36, 'name' => 'Hungary(+36)'),
            array('country_code' => 'IS', 'mobile_code' => 354, 'name' => 'Iceland(+354)'),
            array('country_code' => 'IN', 'mobile_code' => 91, 'name' => 'India(+91)'),
            array('country_code' => 'ID', 'mobile_code' => 62, 'name' => 'Indonesia(+62)'),
            array('country_code' => 'IR', 'mobile_code' => 98, 'name' => 'Iran(+98)'),
            array('country_code' => 'IQ', 'mobile_code' => 964, 'name' => 'Iraq(+964)'),
            array('country_code' => 'IE', 'mobile_code' => 353, 'name' => 'Ireland(+353)'),
            array('country_code' => 'IL', 'mobile_code' => 972, 'name' => 'Israel(+972)'),
            array('country_code' => 'IT', 'mobile_code' => 39, 'name' => 'Italy(+39)'),
            array('country_code' => 'JM', 'mobile_code' => 1876, 'name' => 'Jamaica(+1876)'),
            array('country_code' => 'JP', 'mobile_code' => 81, 'name' => 'Japan(+81)'),
            array('country_code' => 'JO', 'mobile_code' => 962, 'name' => 'Jordan(+962)'),
            array('country_code' => 'KZ', 'mobile_code' => 7, 'name' => 'Kazakhstan(+7)'),
            array('country_code' => 'KE', 'mobile_code' => 254, 'name' => 'Kenya(+254)'),
            array('country_code' => 'KI', 'mobile_code' => 686, 'name' => 'Kiribati(+686)'),
            array('country_code' => 'KP', 'mobile_code' => 850, 'name' => 'KoreaNorth(+850)'),
            array('country_code' => 'KR', 'mobile_code' => 82, 'name' => 'KoreaSouth(+82)'),
            array('country_code' => 'KW', 'mobile_code' => 965, 'name' => 'Kuwait(+965)'),
            array('country_code' => 'KG', 'mobile_code' => 996, 'name' => 'Kyrgyzstan(+996)'),
            array('country_code' => 'LA', 'mobile_code' => 856, 'name' => 'Laos(+856)'),
            array('country_code' => 'LV', 'mobile_code' => 371, 'name' => 'Latvia(+371)'),
            array('country_code' => 'LB', 'mobile_code' => 961, 'name' => 'Lebanon(+961)'),
            array('country_code' => 'LS', 'mobile_code' => 266, 'name' => 'Lesotho(+266)'),
            array('country_code' => 'LR', 'mobile_code' => 231, 'name' => 'Liberia(+231)'),
            array('country_code' => 'LY', 'mobile_code' => 218, 'name' => 'Libya(+218)'),
            array('country_code' => 'LI', 'mobile_code' => 417, 'name' => 'Liechtenstein(+417)'),
            array('country_code' => 'LT', 'mobile_code' => 370, 'name' => 'Lithuania(+370)'),
            array('country_code' => 'LU', 'mobile_code' => 352, 'name' => 'Luxembourg(+352)'),
            array('country_code' => 'MO', 'mobile_code' => 853, 'name' => 'Macao(+853)'),
            array('country_code' => 'MK', 'mobile_code' => 389, 'name' => 'Macedonia(+389)'),
            array('country_code' => 'MG', 'mobile_code' => 261, 'name' => 'Madagascar(+261)'),
            array('country_code' => 'MW', 'mobile_code' => 265, 'name' => 'Malawi(+265)'),
            array('country_code' => 'MY', 'mobile_code' => 60, 'name' => 'Malaysia(+60)'),
            array('country_code' => 'MV', 'mobile_code' => 960, 'name' => 'Maldives(+960)'),
            array('country_code' => 'ML', 'mobile_code' => 223, 'name' => 'Mali(+223)'),
            array('country_code' => 'MT', 'mobile_code' => 356, 'name' => 'Malta(+356)'),
            array('country_code' => 'MH', 'mobile_code' => 692, 'name' => 'MarshallIslands(+692)'),
            array('country_code' => 'MQ', 'mobile_code' => 596, 'name' => 'Martinique(+596)'),
            array('country_code' => 'MR', 'mobile_code' => 222, 'name' => 'Mauritania(+222)'),
            array('country_code' => 'YT', 'mobile_code' => 269, 'name' => 'Mayotte(+269)'),
            array('country_code' => 'MX', 'mobile_code' => 52, 'name' => 'Mexico(+52)'),
            array('country_code' => 'FM', 'mobile_code' => 691, 'name' => 'Micronesia(+691)'),
            array('country_code' => 'MD', 'mobile_code' => 373, 'name' => 'Moldova(+373)'),
            array('country_code' => 'MC', 'mobile_code' => 377, 'name' => 'Monaco(+377)'),
            array('country_code' => 'MN', 'mobile_code' => 976, 'name' => 'Mongolia(+976)'),
            array('country_code' => 'MS', 'mobile_code' => 1664, 'name' => 'Montserrat(+1664)'),
            array('country_code' => 'MA', 'mobile_code' => 212, 'name' => 'Morocco(+212)'),
            array('country_code' => 'MZ', 'mobile_code' => 258, 'name' => 'Mozambique(+258)'),
            array('country_code' => 'MN', 'mobile_code' => 95, 'name' => 'Myanmar(+95)'),
            array('country_code' => 'NA', 'mobile_code' => 264, 'name' => 'Namibia(+264)'),
            array('country_code' => 'NR', 'mobile_code' => 674, 'name' => 'Nauru(+674)'),
            array('country_code' => 'NP', 'mobile_code' => 977, 'name' => 'Nepal(+977)'),
            array('country_code' => 'NL', 'mobile_code' => 31, 'name' => 'Netherlands(+31)'),
            array('country_code' => 'NC', 'mobile_code' => 687, 'name' => 'NewCaledonia(+687)'),
            array('country_code' => 'NZ', 'mobile_code' => 64, 'name' => 'NewZealand(+64)'),
            array('country_code' => 'NI', 'mobile_code' => 505, 'name' => 'Nicaragua(+505)'),
            array('country_code' => 'NE', 'mobile_code' => 227, 'name' => 'Niger(+227)'),
            array('country_code' => 'NG', 'mobile_code' => 234, 'name' => 'Nigeria(+234)'),
            array('country_code' => 'NU', 'mobile_code' => 683, 'name' => 'Niue(+683)'),
            array('country_code' => 'NF', 'mobile_code' => 672, 'name' => 'NorfolkIslands(+672)'),
            array('country_code' => 'NP', 'mobile_code' => 670, 'name' => 'NorthernMarianas(+670)'),
            array('country_code' => 'NO', 'mobile_code' => 47, 'name' => 'Norway(+47)'),
            array('country_code' => 'OM', 'mobile_code' => 968, 'name' => 'Oman(+968)'),
            array('country_code' => 'PW', 'mobile_code' => 680, 'name' => 'Palau(+680)'),
            array('country_code' => 'PA', 'mobile_code' => 507, 'name' => 'Panama(+507)'),
            array('country_code' => 'PG', 'mobile_code' => 675, 'name' => 'PapuaNewGuinea(+675)'),
            array('country_code' => 'PY', 'mobile_code' => 595, 'name' => 'Paraguay(+595)'),
            array('country_code' => 'PE', 'mobile_code' => 51, 'name' => 'Peru(+51)'),
            array('country_code' => 'PH', 'mobile_code' => 63, 'name' => 'Philippines(+63)'),
            array('country_code' => 'PL', 'mobile_code' => 48, 'name' => 'Poland(+48)'),
            array('country_code' => 'PT', 'mobile_code' => 351, 'name' => 'Portugal(+351)'),
            array('country_code' => 'PR', 'mobile_code' => 1787, 'name' => 'PuertoRico(+1787)'),
            array('country_code' => 'QA', 'mobile_code' => 974, 'name' => 'Qatar(+974)'),
            array('country_code' => 'RE', 'mobile_code' => 262, 'name' => 'Reunion(+262)'),
            array('country_code' => 'RO', 'mobile_code' => 40, 'name' => 'Romania(+40)'),
            array('country_code' => 'RU', 'mobile_code' => 7, 'name' => 'Russia(+7)'),
            array('country_code' => 'RW', 'mobile_code' => 250, 'name' => 'Rwanda(+250)'),
            array('country_code' => 'SM', 'mobile_code' => 378, 'name' => 'SanMarino(+378)'),
            array('country_code' => 'ST', 'mobile_code' => 239, 'name' => 'SaoTome & Principe(+239'),
            array('country_code' => 'SA', 'mobile_code' => 966, 'name' => 'SaudiArabia(+966)'),
            array('country_code' => 'SN', 'mobile_code' => 221, 'name' => 'Senegal(+221)'),
            array('country_code' => 'CS', 'mobile_code' => 381, 'name' => 'Serbia(+381)'),
            array('country_code' => 'SC', 'mobile_code' => 248, 'name' => 'Seychelles(+248)'),
            array('country_code' => 'SL', 'mobile_code' => 232, 'name' => 'SierraLeone(+232)'),
            array('country_code' => 'SG', 'mobile_code' => 65, 'name' => 'Singapore(+65)'),
            array('country_code' => 'SK', 'mobile_code' => 421, 'name' => 'SlovakRepublic(+421)'),
            array('country_code' => 'SI', 'mobile_code' => 386, 'name' => 'Slovenia(+386)'),
            array('country_code' => 'SB', 'mobile_code' => 677, 'name' => 'SolomonIslands(+677)'),
            array('country_code' => 'SO', 'mobile_code' => 252, 'name' => 'Somalia(+252)'),
            array('country_code' => 'ZA', 'mobile_code' => 27, 'name' => 'SouthAfrica(+27)'),
            array('country_code' => 'ES', 'mobile_code' => 34, 'name' => 'Spain(+34)'),
            array('country_code' => 'LK', 'mobile_code' => 94, 'name' => 'SriLanka(+94)'),
            array('country_code' => 'SH', 'mobile_code' => 290, 'name' => 'St.Helena(+290)'),
            array('country_code' => 'KN', 'mobile_code' => 1869, 'name' => 'St.Kitts(+1869)'),
            array('country_code' => 'SC', 'mobile_code' => 1758, 'name' => 'St.Lucia(+1758)'),
            array('country_code' => 'SD', 'mobile_code' => 249, 'name' => 'Sudan(+249)'),
            array('country_code' => 'SR', 'mobile_code' => 597, 'name' => 'Suriname(+597)'),
            array('country_code' => 'SZ', 'mobile_code' => 268, 'name' => 'Swaziland(+268)'),
            array('country_code' => 'SE', 'mobile_code' => 46, 'name' => 'Sweden(+46)'),
            array('country_code' => 'CH', 'mobile_code' => 41, 'name' => 'Switzerland(+41)'),
            array('country_code' => 'SI', 'mobile_code' => 963, 'name' => 'Syria(+963)'),
            array('country_code' => 'TW', 'mobile_code' => 886, 'name' => 'Taiwan(+886)'),
            array('country_code' => 'TJ', 'mobile_code' => 7, 'name' => 'Tajikstan(+7)'),
            array('country_code' => 'TH', 'mobile_code' => 66, 'name' => 'Thailand(+66)'),
            array('country_code' => 'TG', 'mobile_code' => 228, 'name' => 'Togo(+228)'),
            array('country_code' => 'TO', 'mobile_code' => 676, 'name' => 'Tonga(+676)'),
            array('country_code' => 'TT', 'mobile_code' => 1868, 'name' => 'Trinidad & Tobago(+1868'),
            array('country_code' => 'TN', 'mobile_code' => 216, 'name' => 'Tunisia(+216)'),
            array('country_code' => 'TR', 'mobile_code' => 90, 'name' => 'Turkey(+90)'),
            array('country_code' => 'TM', 'mobile_code' => 7, 'name' => 'Turkmenistan(+7)'),
            array('country_code' => 'TM', 'mobile_code' => 993, 'name' => 'Turkmenistan(+993)'),
            array('country_code' => 'TC', 'mobile_code' => 1649, 'name' => 'Turks & CaicosIslands(+1649)'),
            array('country_code' => 'TV', 'mobile_code' => 688, 'name' => 'Tuvalu(+688)'),
            array('country_code' => 'UG', 'mobile_code' => 256, 'name' => 'Uganda(+256)'),
            array('country_code' => 'GB', 'mobile_code' => 44, 'name' => 'UK(+44)'),
            array('country_code' => 'UA', 'mobile_code' => 380, 'name' => 'Ukraine(+380)'),
            array('country_code' => 'AE', 'mobile_code' => 971, 'name' => 'UnitedArabEmirates(+971)'),
            array('country_code' => 'UY', 'mobile_code' => 598, 'name' => 'Uruguay(+598)'),
            array('country_code' => 'US', 'mobile_code' => 1, 'name' => 'USA(+1)'),
            array('country_code' => 'UZ', 'mobile_code' => 7, 'name' => 'Uzbekistan(+7)'),
            array('country_code' => 'VU', 'mobile_code' => 678, 'name' => 'Vanuatu(+678)'),
            array('country_code' => 'VA', 'mobile_code' => 379, 'name' => 'VaticanCity(+379)'),
            array('country_code' => 'VE', 'mobile_code' => 58, 'name' => 'Venezuela(+58)'),
            array('country_code' => 'VN', 'mobile_code' => 84, 'name' => 'Vietnam(+84)'),
            array('country_code' => 'VG', 'mobile_code' => 84, 'name' => 'VirginIslands-British(+1284)'),
            array('country_code' => 'VI', 'mobile_code' => 84, 'name' => 'VirginIslands-US(+1340)'),
            array('country_code' => 'WF', 'mobile_code' => 681, 'name' => 'Wallis & Futuna(+681)'),
            array('country_code' => 'YE', 'mobile_code' => 969, 'name' => 'Yemen(North)(+969)'),
            array('country_code' => 'YE', 'mobile_code' => 967, 'name' => 'Yemen(South)(+967)'),
            array('country_code' => 'ZM', 'mobile_code' => 260, 'name' => 'Zimbabwe(+263)'),
            array('country_code' => 'ZW', 'mobile_code' => 263, 'name' => 'Zambia(+260)'),
        

        );
        CountryCode::insert($data);
    }
}
